Error: Add InvalidInteger error type
Invalid integers are any block of characters starting with an ascii
digit but contain non-ascii digit characters. Jack does NOT support
hexadecmial digits. (at least not according to its spec but I may throw
them in there later ;)...)

Examples
    - let x = 38ab;
    - let x = 8837{;
    - etc.